name: Build for ArchLinux

on:
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cleanup system
        uses: rokibhasansagar/slimhub_actions@main

      - name: Upgrade system
        uses: docker://archlinux:latest
        with:
          args: |-
            pacman --sync --refresh --sysupgrade --noconfirm

      - name: Install required packages
        uses: docker://archlinux:latest
        with:
          args: |-
            pacman --sync --noconfirm --needed python-pytorch-rocm

      - name: Install dependencies
        uses: docker://archlinux:latest
        with:
          args: |-
            python -m pip install build wheel safetensors==0.3.1 sentencepiece>=0.1.97 ninja==1.11.1

      - name: Build package
        uses: docker://archlinux:latest
        with:
          args: |-
            PYTORCH_ROCM_ARCH=gfx803 python -m build --no-isolation --wheel

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |-
            dist/*.whl
